# Generated by Django 5.2.8 on 2025-11-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asetmesin',
            options={'verbose_name': 'Aset Mesin', 'verbose_name_plural': 'Daftar Aset Mesin'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Lampiran', 'verbose_name_plural': 'Daftar Lampiran'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Pengguna', 'verbose_name_plural': 'Daftar Pengguna'},
        ),
        migrations.AlterModelOptions(
            name='jabatan',
            options={'verbose_name': 'Jabatan', 'verbose_name_plural': 'Daftar Jabatan'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Pekerjaan (Job)', 'verbose_name_plural': 'Daftar Pekerjaan (Job)'},
        ),
        migrations.AlterModelOptions(
            name='jobdate',
            options={'ordering': ['tanggal'], 'verbose_name': 'Tanggal Pengerjaan', 'verbose_name_plural': 'Tanggal Pengerjaan'},
        ),
        migrations.AlterModelOptions(
            name='personil',
            options={'verbose_name': 'Personil', 'verbose_name_plural': 'Daftar Personil'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Daftar Project'},
        ),
    ]
