# Generated by Django 5.2.8 on 2025-11-18 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_asetmesin_options_alter_attachment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='personil_ditugaskan',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='personil_ditugaskan',
            field=models.ManyToManyField(blank=True, help_text='Pilih satu atau beberapa personil', related_name='jobs_assigned', to='core.personil'),
        ),
    ]
