# Generated by Django 5.2.8 on 2025-11-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_job_personil_ditugaskan_alter_job_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdate',
            name='catatan',
            field=models.TextField(blank=True, help_text='Catatan untuk pekerjaan di tanggal ini', null=True),
        ),
        migrations.AddField(
            model_name='jobdate',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Done', 'Done'), ('Pending', 'Pending'), ('N/A', 'N/A')], default='Open', max_length=10),
        ),
    ]
