# Generated by Django 5.2.8 on 2025-11-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jobdate_catatan_jobdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='fokus',
            field=models.CharField(blank=True, choices=[('Perawatan', 'Perawatan'), ('Perbaikan', 'Perbaikan'), ('Proyek', 'Proyek'), ('Lainnya', 'Lainnya')], default='Perawatan', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='prioritas',
            field=models.CharField(blank=True, choices=[('P1', 'P1 - Mendesak'), ('P2', 'P2 - Tinggi'), ('P3', 'P3 - Normal'), ('P4', 'P4 - Rendah')], default='P3', max_length=10, null=True),
        ),
    ]
