# Generated by Django 5.2.8 on 2025-11-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_fokus_job_prioritas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asetmesin',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
