# Generated by Django 5.2.8 on 2025-11-24 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_asetmesin_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Bawahan yang ditugaskan job ini (opsional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_assigned_to_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
