# Generated by Django 5.2.8 on 2025-11-26 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_job_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_orang', models.CharField(max_length=255)),
                ('tipe_leave', models.CharField(choices=[('Ijin', 'Ijin'), ('Cuti', 'Cuti')], default='Ijin', max_length=10)),
                ('tanggal', models.TextField(help_text='Tanggal single atau range (comma-separated). Format: YYYY-MM-DD')),
                ('deskripsi', models.TextField(blank=True, help_text='Keterangan tambahan', null=True)),
                ('google_event_id', models.CharField(blank=True, help_text='Event ID dari Google Calendar', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Event',
                'verbose_name_plural': 'Daftar Leave Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
