# Generated by Django 5.2.8 on 2025-11-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_leaveevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(help_text='Nomor Induk Karyawan', max_length=20, unique=True, verbose_name='NIK')),
                ('nama_lengkap', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('departemen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departemen')),
                ('posisi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Posisi')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif'), ('Cuti', 'Cuti'), ('Keluar', 'Keluar')], default='Aktif', max_length=50, verbose_name='Status Karyawan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Karyawan',
                'verbose_name_plural': 'Daftar Karyawan',
                'ordering': ['nik'],
            },
        ),
        migrations.AlterField(
            model_name='leaveevent',
            name='nama_orang',
            field=models.CharField(blank=True, help_text='Deprecated - gunakan karyawan field', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaveevent',
            name='karyawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_events', to='core.karyawan', verbose_name='Karyawan'),
        ),
    ]
